spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${1428b053cb483d0c3f89}
            clientSecret:  ${e3cd119dbf1df23063ee5d7bcf07baca8501f0eb}